### ISSUE TITLE
Creating views from view models

### ISSUE THREAD

**Issue by abrasat** [CodonFramework/Codon#1]
Is it possible to use the default dependency IoC Container from Codon.Framework to construct views from view-models ?
I have a MasterDetailPage based application in mind, where the views (Detail pages) should be constructed from the view-model of the actually selected menu item in the Master page.
The ViewModels would all be derived from the Codon.Framework ViewModelBase class (IViewModel interface), and the corresponding ContentPages used for the Detail Pages could if necessary be derived from some kind of IViewFor<> generic interface, realizing the "link" to the view-model to be used as BindingContext.
I am thinking to something similar to the ViewFactory from XLabs.

**Comment by DVaughan** [comment]
You could register a factory class with the container that is able to generate a view from a view-model. 
Another approach is to create an interface (e.g., IFooView) that represents the view. Your view-models could then declare a property (or be decorated with an attribute) such as public Type ViewType { get; }
You could then use that information to resolve the concrete view by registering a lambda expression with the container that resolves the interface type to the actual view type.
There are a few approaches here.
