### ISSUE TITLE
Call to Dependency.Resolve<T>() crashes iOS application

### ISSUE THREAD

**Issue by abrasat** [CodonFramework/Codon#11]
The call to Dependency.Resolve<T>() for a Xamarin.Forms iOS application leads to the crash of the application.
I am using latest Codon 2.07. Alpha. The problem can re reproduced with the FormsStarter sample [https://github.com/CodonFramework/Samples/files/964251/FormsStarter.zip](https://github.com/CodonFramework/Samples/files/964251/FormsStarter.zip) , it occurs at the first call when trying to resolve ILog (I tested it with the iOS Simulator on a MacBook) .

```
    class Bootstrapper
    {
	    public void Run()
	    {
                var log = Dependency.Resolve<ILog>();
```

**Comment by DVaughan** [comment]
Please try updating your Xamarin related packages. Are you using version 2.4.0.280 for the iOS project?
I am able to launch the app in the simulator without experiencing the exception.

**Comment by abrasat** [comment]
I am using Xamarin.Forms 2.4.0.282 for the iOS project and the problem still occurs.

I am also using Visual Studio 2017 with latest version 15.3.5 and Xamarin.iOS version 11.0 on the MacBook where the project is cross-compiled and where the iOS Simulator is running.
What versions did you use for your tests ?

**Comment by DVaughan** [comment]
It appears to be a quirk with Xamarin.iOS related to type resolution. Here's a work around. In static void Main(string[] args) in your iOS Application class, add the following:
```csharp
public class Application
{
	// This is the main entry point of the application.
	static void Main(string[] args)
	{
		Type type = typeof(PlatformIdentifier);
		UIApplication.Main(args, null, "AppDelegate");
	}
}
```

**Comment by abrasat** [comment]
The workaround helped, thanks.
Are you planning to integrate the workaround in the next Codon framework release ?

**Comment by DVaughan** [comment]
It looks to me as a Xamarin iOS limitation or bug. Codon doesn't require a bootstrapper or calling of an initialization method, so I believe it would be the wrong thing to do to introduce one just to combat this external issue.
