### ISSUE TITLE
Android ImageView binding

### ISSUE THREAD

**Issue by takacsalbert** [CodonFramework/Codon#12]
Hi,
I intend to use Codon in a Xamarin Android project, but I have a question. Does Codon support binding a Drawable type property to ImageView? I think this could be achieved by calling SetImageDrawable(...).
I've tried out Calcium, which is awesome for binding almost everything I need, except ImageView. The binding part looks like it is coming from Calcium, am I right? ;)

Thank you for your kind answer!

Best Regards,
Albert Takács

**Comment by DVaughan** [comment]
The binding support has grown a lot for Android and is rather extensible. Sorry there's not more documentation on that yet.
I just had a quick peek at how I did that in one of my own projects and I used:
```xml
l:Binding="Target=SetImageBitmap, Path=Favicon"
```
where Favicon is a Android.Graphics.Bitmap

Let me know if that works for you, otherwise I'll give you a hand to find something that does.

Cheers,
Daniel

**Comment by DVaughan** [comment]
More to the particulars of your question (I was a bit quick to reply) you can use the following to bind to a Drawable:

```xml
l:Binding="Target=SetImageDrawable, Path=Theme.ViewBackground"
```

**Comment by takacsalbert** [comment]
Awesome. Works flawlessly. I use akavache/splat to have cached images in my shared PCL library on my VMs. I wrote a simple valueconverter that turns splat IBitmap to Android native Drawable. Then I just used Codon binding you mentioned.
I only had to replace Calcium to Codon, and replace Source to Path in the bindings.
Only one thing does not work: ListView binding. I have it already from Calcium. Can you please guide me how to do that?
I am sure I am going to use your sdk in my Elllo English Learning app (and in others as well). I already have it for Windows, and I am currently working on the Android version. (you can take a look at it if you mind: https://www.microsoft.com/store/apps/9wzdncrdff1g)
Thanks for helping me out!
