### ISSUE TITLE
ListView binding

### ISSUE THREAD

**Issue by takacsalbert** [CodonFramework/Codon#13]
Hi,
What is the correct way to do ListView item source and item click binding? Can you please give me a guide?
Thanks,
Albert

**Comment by DVaughan** [comment]
The way I usually do that is by using a binding, like so:

```xml
l:Binding="Target=Adapter, Path=MyObservableCollectionProperty, Converter={Ioc extrasPlatform:ListAdapterConverter}, ConverterParameter=@layout/MyLayoutForEachItemInCollection"
```

The converter does the heavy lifting of hooking up your collection to an adapter. You do, however, need to register the namespace of the converter in your bootstrapper, like so:

```cs
var aliasRegistry = Dependency.Resolve<INamespaceAliasRegistry, NamespaceAliasRegistry>(true);
aliasRegistry.RegisterNamespaceAlias("extrasPlatform", "Codon.UI.Elements", "Codon.Extras.Platform");
```

I'll devise a way to streamline the namespace registration in a future iteration.

To subscribe to an item click, add this to the ListView's l:Binding attribute:

```xml
Target=ItemClick, Path=HandleItemClick
```

In the end it will look something like this:
```xml
l:Binding="Target=Adapter, Path=MyObservableCollectionProperty, Converter={Ioc extrasPlatform:ListAdapterConverter}, ConverterParameter=@layout/MyLayoutForEachItemInCollection; Target=ItemClick, Path=HandleItemClick"
```

**Comment by takacsalbert** [comment]
Hi,

Thanks for the detailed tutorial!
I have only one thing that I couldn't come across. It is the converter part:
`Converter={Ioc extrasPlatform:ListAdapterConverter}`

I am not sure if "Ioc" is a keyword or shortcut to your own ioc container, or is it a property on my ViewModel. I have my own ioc container that comes from the MVVMLight framework, which I don't want to replace at the moment.

Can you please clarify this one, because I cannot make it work. Big thanks!

**Comment by takacsalbert** [comment]
Oh I just made it work. I registered the NamespaceAliasRegistry to Codon.Dependency and it is working now. I have it besides my own container because they do not interfere.

**Comment by DVaughan** [comment]
Are you using MVVMLight alongside Codon?

**Comment by takacsalbert** [comment]
Yeah, I am using MVVMLight

**Comment by DVaughan** [comment]
If I were you I'd look at the feature overlap and reconsider. Package size and startup performance can be unduly affected by unnecessary assembly references. 
I'd be surprised if you found anything in MVVMLight that Codon doesn't do better.

**Comment by takacsalbert** [comment]
I'll look into this, thanks for the heads up.
