### ISSUE TITLE
IDialogService - await dialog result

### ISSUE THREAD

**Issue by abrasat** [CodonFramework/Codon#16]
Is it possible to await the result of a dialog from DialogService with several options (AskYesNoQuestion, AskYesNoCancelQuestion, AskOkCancelQuestion), displayed in an ActionCommand (triggered by clicking a button bound to it), or in a ReceiveMessageAsync() method ? I could not find any samples with such scenarios (all samples use ShowMessageAsync() without awaiting any result).
Does Codon support asynchronous commands ?

**Comment by DVaughan** [comment]
Yes to both.

Use the `IDialogService`'s awaitable `AskYesNoQuestionAsync`, `AskOkCancelQuestionAsync` etc., to await the result. 

Codon does support asynchronous commands. See the `AsyncActionCommand` and `AsyncUICommand` classes, located in the Extras library.

**Comment by abrasat** [comment]
Thx, I will take a look at these classes.

**Comment by abrasat** [comment]
Is it possible to open also customized pop-up pages through the DialogService (for instance one containing Yes, Cancel buttons and a text field) ?

**Comment by DVaughan** [comment]
For a text input you can use the IDialogService.AskQuestionAsync

```csharp
var question = new TextQuestion(string.Empty)
				{
					DefaultResponse = string.Empty,
					Caption = AppResources.AppBar_MenuItem_FindOnPage,
					InputScope = InputScopeNameValue.Text
				};

				var questionResponse = await DialogService.AskQuestionAsync(question);
				if (questionResponse == null || questionResponse.Response == null
					|| !questionResponse.Response.HasValidAnswer
					|| questionResponse.Response.OkCancelQuestionResult != OkCancelQuestionResult.OK)
				{
					return;
				}

var searchText = questionResponse.Response.Text;
```

If you need something more complex, use ShowDialogAsync and pass in a view as the content.
