### ISSUE TITLE
Xamarin Android ActionCommand Update

### ISSUE THREAD

**Issue by kappesLab** [CodonFramework/Codon#18]
When the `Func<obj,bool>()` return a new value (Example: from **_true_** to **_false_**) the Android Activity is not automatic update. It is necessary to manually invoke the `RaiseCanExecuteChanged()` on the `ActionCommand` object.

**Comment by DVaughan** [comment]
That's right. ActionCommands are not aware of the lifecycle of the Android Activity.

**Comment by kappesLab** [comment]
Is the strategy of launching the event manually correct ? Is there a better way to update android Activity or not?

**Comment by DVaughan** [comment]
When your view becomes active you can tell the view-model to refresh its commands. That's one way.
