### ISSUE TITLE
EditText TwoWay binding

### ISSUE THREAD

**Issue by takacsalbert** [CodonFramework/Codon#19]
Hi Daniel,

I am trying to make two way binding on an EditText widget, but with no luck. Other modes of bindings work ok on this layout. I use Codon v2.0.8. The VM implements INotifyPropertyChanged. Thanks for helping me out.

Actual layout code:
<EditText android:layout_width="match_parent"
              android:layout_height="wrap_content"
              android:id="@+id/ReadAloud_Text"
              local:Binding="Target=Text, Path=Text, Mode=TwoWay"/>

I get the following error message in the output:
Debug Log Debug - Unable to locate value changed event for two way binding with target Text on AppCompatEditText. Target does not implement INotifyPropertyChanged. member:Bind file:C:\Repos\Codon\Framework\Source\Framework\Codon.UI.Data\DataBinding\InternalBindingApplicator.Bind.cs line:454 exception:02-20 16:21:22.882 I/mono-stdout( 7395): Debug Log Debug - Unable to locate value changed event for two way binding with target Text on AppCompatEditText. Target does not implement INotifyPropertyChanged. member:Bind file:C:\Repos\Codon\Framework\Source\Framework\Codon.UI.Data\DataBinding\InternalBindingApplicator.Bind.cs line:454 exception:

**Comment by DVaughan** [comment]
You need to either register the AppCompatEditText like so:
```csharp
InternalBindingApplicator.ViewBinderRegistry.SetViewBinder<AppCompatEditText>(nameof(AppCompatEditText.Text), new ViewEventBinder<AppCompatEditText, Android.Text.TextChangedEventArgs, string>(
				(view, h) => view.TextChanged += h, (view, h) => view.TextChanged -= h, (view, args) => args.Text.ToString()));
```
Or specify the update event in the binding, like so:
```csharp
l:Binding="{Target=Text, Path=MyText, Mode=TwoWay, ChangedEvent=TextChanged}"
```
By the way, you can register a whole bunch of binding events using the `InternalBindingApplicator.ViewBinderRegistry.SetViewBinders(IDictionary)` method.

**Comment by takacsalbert** [comment]
Thanks Daniel,
This works like charm:
`l:Binding="{Target=Text, Path=MyText, Mode=TwoWay, ChangedEvent=TextChanged}"`
