### ISSUE TITLE
Log message that I do not understand

### ISSUE THREAD

**Issue by kappesLab** [CodonFramework/Codon#21]
When I text my Adroid aplication in the output window of VS I receive this message from the codon framework:

`Debug Log Debug - Unable to resolve type using DefaultTypeNameAttribute with value: Codon.Concurrency.UISynchronizationContext, Codon.Platform member:ResolveCore file:C:\Repos\Codon\Framework\Source\Framework\Codon\InversionOfControl\Containers\FrameworkContainer.cs line:650 exception:`
`02-25 19:08:27.296 I/mono-stdout(25891): Debug Log Debug - Unable to resolve type using DefaultTypeNameAttribute with value: Codon.Concurrency.UISynchronizationContext, Codon.Platform member:ResolveCore file:C:\Repos\Codon\Framework\Source\Framework\Codon\InversionOfControl\Containers\FrameworkContainer.cs line:650 exception:`

the application seems to work properly, I can't understand what that message generates.

**Comment by DVaughan** [comment]
Codon's isn't able to locate the UISynchronization class. Have you referenced the NuGet package for Codon Android?

**Comment by kappesLab** [comment]
Yes, I should have it

![picture](https://user-images.githubusercontent.com/36405345/36645882-8c8a11dc-1a6f-11e8-83c3-5e0f74edfb4b.png)

**Comment by kappesLab** [comment]
I would like to inform you that I receive such messages also by following the example provided on https://github.com/CodonFramework/Samples . What can this depend on?

**Comment by DVaughan** [comment]
Ignore the message. It's a debug level message from the IoC container telling you that it tried to find a platform specific version of the UISynchronizationContext class, but it couldn't find one. It falls back to the non-platform specific UISynchronizationContext. You can see how default types are specified by looking at the ISynchronizationContext interface.

**Comment by kappesLab** [comment]
Ok, thank you for the explanation, now I am more relaxed.
