### ISSUE TITLE
NullReferenceException when applying binding on Visibility and it is set to "Gone"

### ISSUE THREAD

**Issue by takacsalbert** [CodonFramework/Codon#23]
Hi,
I am experiencing NullReferenceException  raised for BindingApplicator.ApplyBindings(...) when the layout contains a binding on a Visibility property, and the source is evaluated to "Gone". I want to have some views hidden by default and reveal them later.
I am using a ValueConverter to convert a boolean value to Visibility value.
Can you please let me know how can I resolve this issue? Thanks in advance.

Here is the stack trace:
I/MonoDroid( 3157): System.ArgumentException: Exception raised using setter delegate to set property. Source: RD.Shared.ViewModels.PPageViewModel.IsShowResult, Target: android.widget.LinearLayout{4c6f5b1 V.E...... ......I. 0,0-0,0 #7f0c0085 app:id/PLayout_Results}.Visibility ---> System.NullReferenceException: Object reference not set to an instance of an object.
I/MonoDroid( 3157):   at (wrapper dynamic-method) System.Object.lambda_method(System.Runtime.CompilerServices.Closure,object,object)
I/MonoDroid( 3157):   at Codon.UI.Data.InternalBindingApplicator.SetTargetProperty (System.Reflection.PropertyInfo sourceProperty, System.Object dataContext, System.Object view, System.Reflection.PropertyInfo targetProperty, Codon.MissingTypes.System.Windows.Data.IValueConverter converter, System.String converterParameter) [0x0007c] in C:\Repos\Codon\Framework\Source\Framework\Codon.UI.Data\DataBinding\InternalBindingApplicator.TargetValueAssigners.cs:64 
I/MonoDroid( 3157):    --- End of inner exception stack trace ---
I/MonoDroid( 3157):   at Codon.UI.Data.InternalBindingApplicator.SetTargetProperty (System.Reflection.PropertyInfo sourceProperty, System.Object dataContext, System.Object view, System.Reflection.PropertyInfo targetProperty, Codon.MissingTypes.System.Windows.Data.IValueConverter converter, System.String converterParameter) [0x00089] in C:\Repos\Codon\Framework\Source\Framework\Codon.UI.Data\DataBinding\InternalBindingApplicator.TargetValueAssigners.cs:68 
I/MonoDroid( 3157):   at Codon.UI.Data.InternalBindingApplicator+<>c__DisplayClass1_7.<Bind>b__9 () [0x0000d] in C:\Repos\Codon\Framework\Source\Framework\Codon.UI.Data\DataBinding\InternalBindingApplicator.Bind.cs:380 
I/MonoDroid( 3157):   at Codon.Concurrency.UISynchronizationContext+<>c__DisplayClass7_0.<GetWrappedAction>b__0 () [0x0004a] in C:\Repos\Codon\Framework\Source\Framework\Codon\Concurrency\Synchronization\UISynchronizationContext.ActionWrapping.cs:136 
I/MonoDroid( 3157):   at Codon.Concurrency.UISynchronizationContext.Send (System.Action action, System.String memberName, System.String filePath, System.Int32 lineNumber) [0x00057] in C:\Repos\Codon\Framework\Source\Framework\Codon\Concurrency\Synchronization\UISynchronizationContext.cs:98 
I/MonoDroid( 3157):   at Codon.UI.Data.InternalBindingApplicator.Bind (Codon.UI.Data.BindingExpression bindingExpression, System.Object dataContext, System.String[] sourcePath, Codon.MissingTypes.System.Windows.Data.IValueConverter converter, System.Reflection.PropertyInfo targetProperty, System.Collections.Generic.IList`1[T] localRemoveActions, System.Collections.Generic.IList`1[T] globalRemoveActions, System.Int32 position) [0x0096e] in C:\Repos\Codon\Framework\Source\Framework\Codon.UI.Data\DataBinding\InternalBindingApplicator.Bind.cs:375 
I/MonoDroid( 3157):   at Codon.UI.Data.InternalBindingApplicator.ApplyBinding (Codon.UI.Data.BindingExpression bindingExpression, System.Object activity, System.String dataContextPropertyOnActivity, Codon.MissingTypes.System.Windows.Data.IValueConverter converter, System.Collections.Generic.List`1[T] unbindActions) [0x0007a] in C:\Repos\Codon\Framework\Source\Framework\Codon.UI.Data\DataBinding\InternalBindingApplicator.cs:85 
I/MonoDroid( 3157):   at Codon.UI.Data.XmlBindingApplicator.ApplyBindings (Android.App.Activity activity, System.String viewModelPropertyName, System.Int32 layoutResourceId) [0x001a9] in C:\Repos\Codon\Framework\Source\Framework\Platforms\Android\Codon.Extras.Platform\UI\Data\XmlBindingApplicator.Android.cs:175 
I/MonoDroid( 3157):   at RD.Droid.Activities.PActivity.OnCreate (Android.OS.Bundle savedInstanceState) [0x00145] in C:\repo\RD\src\RD.Droid\Activities\PActivity.cs:48

**Comment by DVaughan** [comment]
Are you using Codon's BooleanToVisibilityConverter? If so, are you specifying visibility states with the ConverterParameter?

**Comment by takacsalbert** [comment]
No, I use my own converter.

local:Binding="Path=IsShowResult, Target=Visibility, Mode=OneWay, Converter=BoolToVisibilityConverter"

It goes like this:
`using Android.Views;
using Codon.MissingTypes.System.Windows.Data;
using System;
using System.Globalization;

namespace RD.Droid.Converters
{
    public class BoolToCollapsedConverter : IValueConverter
    {
        public object Convert(object value, Type targetType, object parameter, CultureInfo culture)
        {
            var val = System.Convert.ToBoolean(value);

            if (val)
                return ViewStates.Gone;

            return ViewStates.Visible;
        }

        public object ConvertBack(object value, Type targetType, object parameter, CultureInfo culture)
        {
            throw new NotImplementedException();
        }
    }
}`

**Comment by DVaughan** [comment]
I don't know what's going on there. You can send me a small repro and I'll take a look at it for you. 

Alternatively you may want to try the Codon converter since it supports the three states out of the box. Here's an example of how to use it:

```xml
l:Binding="Target=Url, Path=Url; Target=Visibility, Path=RequirePasscode, Converter={StaticResource BooleanToVisibilityConverter}, ConverterParameter=Gone\\,Visible\\,Invisible"
```
The converter parameter allows you to specify the three states. The position of the three states translate to the following: <Visibility when true>\\,<Visibility when false>\\,<Visibility when null>

So, the example shows that when RequirePasscode is true, the visibility will be Gone; when RequirePasscode is false, the visibility is Visible; and when value can't be resolved for whatever reason, the visibility is Invisible.

If no ConverterParameter is supplied then it defaults to Visible\\,Invisible\\,Visible

**Comment by takacsalbert** [comment]
Hi Daniel,

Thanks for your kind help. I tried the Codon converter, and the error is the same.

Here is the setup. I have my VM in a separate .NET Standard 2.0 project. I use MVVM Light. There is a VM that has a bool property:
```
private bool _IsShowResult;
public bool IsShowResult
{
get { return _IsShowResult; }
set { Set(ref _IsShowResult, value); }
}
```
I have a layout where there is a View like this:
```
<LinearLayout android:layout_width="wrap_content"
                  android:layout_height="wrap_content"
                  android:orientation="horizontal"
                  android:layout_gravity="top|right"
                  android:id="@+id/PlayingLayout_Results"
                  local:Binding="Path=IsShowResult, Target=Visibility, Mode=OneWay, Converter={StaticResource BooleanToVisibilityConverter}, ConverterParameter=Visible\\,Gone\\,Gone">
        <TextView android:layout_width="wrap_content"
                  android:layout_height="wrap_content"
                  android:textColor="@android:color/white"
                  android:text="*score: "/>
        <TextView android:layout_width="wrap_content"
                  android:layout_height="wrap_content"
                  android:gravity="center"
                  android:textColor="@android:color/white"
                  android:id="@+id/PlayingLayout_Score"
                  local:Binding="Path=Level.ScorePercent, Target=Text, Mode=OneWay"/>
    </LinearLayout>
```

When the Activity is loaded, after SetContentView(...) I call BindingApplicator.ApplyBindings(...), and I get this error.
```
Unhandled Exception:
System.ArgumentException: Exception raised using setter delegate to set property. Source: ReDraw.Shared.ViewModels.PlayingPageViewModel.IsShowResult, Target: android.widget.LinearLayout{ef6db35 V.E...... ......I. 0,0-0,0 #7f0c0085 app:id/PlayingLayout_Results}.Visibility occurred
```

It seems to be that only Visibility is causing issues. When I take out the binding on the Visibility, everything works fine.

**Comment by DVaughan** [comment]
Not sure. Seems like your view-model is null. If you would create me a repro that would help me solve it.

**Comment by takacsalbert** [comment]
Hi,
This can be reproduced also with your Sample001.
Please overwrite the files from the zip. (I just added a property called IsSomething and a new TextLayout with Visibility binding, nothing else is changed)
[Sample001.zip](https://github.com/CodonFramework/Codon/files/2372541/Sample001.zip)

Please let me know if you need more information. Probably I could reference directly Codon and debug it to see what happens.

**Comment by DVaughan** [comment]
Please include the csproj or sln.

**Comment by DVaughan** [comment]
The Android projects wouldn't load for me.
But I assembled your view-model and view and was able to toggle the visibility.
I forgot to mention that you need to register static resources, like so: 

```cs
var staticResourceRegistry = Dependency.Resolve<IStaticResourceRegistry, StaticResourceRegistry>();		
staticResourceRegistry["BooleanToVisibilityConverter"] = new BooleanToVisibilityConverter();
```

[AndroidVisibilityTest.zip](https://github.com/CodonFramework/Codon/files/2372923/AndroidVisibilityTest.zip)

Btw what do you feel is lacking in Codon that you aren't using it rather than mvvm light? You know Codon's .NET Standard base library has no dependencies. Just curious.

**Comment by takacsalbert** [comment]
>  I forgot to mention that you need to register static resources, like so:

Thanks Daniel! This is the solution. This way it is working as expected. I believe I can register custom converters this way, right?

Can you please mention this also in the documentation? I haven't find any reference for this.
Your work is amazing, but it is hard to find the information to fully utilize the power of Codon.

I am using MVVMLight because I got used to it. I have used it for ages. It allows me to do things the way I feel, and it is transparent and lightweight and goes well with other third parties. I am sure Codon is the same, I just didn't want to port existing code to a whole new library. I hope you understand what I mean. For me, Codon is perfect for Android bindings and hopefully for iOS too. I could have been choosing MVVMCross, but I felt that it is forcing me to do things their way, which I don't like. I like to have the freedom of changing the architecture and the way it works.

**Comment by DVaughan** [comment]
Yes, I need to put in some missing documentation for the Android bits.

Yes, you can use the `IStaticResourceRegistry` to register your own converters or Source objects. 

In addition to the StaticResource markup extension, extensions for the IOC container and Static classes also exist. 

```xml
l:Binding="Target=SetBackgroundColor, Path=AppBarBackgroundColor.Color, Source={Ioc t:Theme}"
```
You can create your own markup extensions by implementing `Codon.UI.Data.IMarkupExtension` and placing it in the `IMarkupExtensionRegistry`.

If you're not using Codon for your view-models then you're missing out on a few things like thread-safe property change notification, change cancellation, and exception management for ICommands. The INPC infrastructure is also not tied to a view-model base class.

**Comment by takacsalbert** [comment]
Cool thanks!

I already released one of my apps to Android using your library. If you don't mind, please check it out:
https://play.google.com/store/apps/details?id=com.takacsalbert.elllo

I am currently working on my other pet project named ReDraw! to bring it to Android. I am also planning to use Codon for my upcoming professional projects (Android, iOS). I would be really grateful if a comprehensive documentation or sample is available with all the amazing features.

I think I close this issue as it is solved with the registration.

**Comment by DVaughan** [comment]
Congrats on the app! 
Please let me know when you publish your other public projects.

**Comment by takacsalbert** [comment]
Sure. You can mention my app that use Codon if you feel like. I would appreciate it. ;)
