### ISSUE TITLE
Event to command?

### ISSUE THREAD

**Issue by Myrmex** [CodonFramework/Codon#25]
Hello, I'm playing with this framework and I was wondering if there is anything like an "event to command" behavior builtin, or any other mechanism devised to let me handle a WPF control's event in the viewmodel (e.g. a `Navigating` event in a `WebBrowser` control).

**Comment by Myrmex** [comment]
Thanks, I like the lightweight approach of this framework, hope to see it grow (have you considered integrating it in <https://github.com/Microsoft/WindowsTemplateStudio>?).

I'd have some more questions, arising from a toy app I'm developing to put Codon at work with a realistic example. I try to list a couple of them here, maybe these are useful hints for newcomers:

1. a typical "debounce" scenario in a bound TextBox. Outside of a RX-based solution, I can use helpers like this: <https://weblog.west-wind.com/posts/2017/jul/02/debouncing-and-throttling-dispatcher-events>. Yet, how could I insert this in a data binding between view and viewmodel? A trivial workaround would be just handling the `KeyUp` event of the `TextBox` in the view, debounce, and set the corresponding VM property, like this:

```cs
private void Search_KeyUp(object sender, KeyEventArgs e)
{
    _debounceTimer.Debounce(500, _ =>
    {
        ViewModel.Browser.SearchText = ((TextBox)sender).Text;
    });
}
```

Yet, this would effectively make the data flow 1-way, from the control to the VM, but not vice-versa, as there is no effective data binding but just an event, which after debouncing triggers a change in the VM. Which approach would you recommend here?

2. composing views like in more complex framework. This is probably asking too much from a lite framework. Anyway, say I have a typical list-and-details UI, where a VM represents a list, and another one the details of a selected item. Each has its logic incapsulated in its own VM and the VMs communicate via messaging (e.g. the list VM publishes a "selected" message and the details VM handles it). Now, I must compose these VMs into a unit: I can just add a third, "shell" VM including an instance of both, and a corresponding view bound to this shell VM. This is OK, but of course forces me to design a single UI for two different VMs. Or is there any better approach?

**Comment by DVaughan** [comment]
1. You could use the Delay property of the Binding in WPF, as @RickStrahl demonstrated in his article.
As you mention though, with a two-way binding your source may update the target when there is a pending update from the target.

2. The way I usually do that is to define a `Codon.UIModel.ICompositeViewModel`. That way you can get some support for navigation events (child view-models can cancel navigation) and state. Though I don't much use the state support these days. The way that I've used the composite support for navigation is within tabbed interfaces; when navigating away from the view, the view-model for each tab has the opportunity to cancel the navigation.

**Comment by Myrmex** [comment]
Thanks, your answers were extraordinarily quick, and very useful!

**Comment by DVaughan** [comment]
You're welcome.
