### ISSUE TITLE
SettingsService for reading parameters from json file ?

### ISSUE THREAD

**Issue by abrasat** [CodonFramework/Codon#3]
Can the Codon settings service be used also for more complex scenarios, like reading parameters from a json file (or even sqlite database, as you mentioned in the "getting started" guides) ?
If yes, could you please add some sample code for such cases ?

**Comment by DVaughan** [comment]
Yes, you just need to implement Codon.SettingsModel.ISettingsStore. Take a look at the [LocalSettingsStore class](https://github.com/CodonFramework/Codon/blob/d0f7cd99ed4ae01a304d260fbc831d9b45099857/Source/Framework/Codon/SettingsModel/SettingsStores/LocalSettingsStore.cs), which uses Mono's IsolatedStorageSettings for iOS and Android, .NET's for UWP, and a custom IsolatedStorageSettings for WPF. 
Once you've implemented ISettingsStore for json or whatever, create an instance of Codon.SettingsModel.SettingsService passing the ISettingsStore to its constructor.

For Sqlite, it's pretty straight forward, but the implementation depends on the which library you're using for Sqlite. I'm using a modified version of Frank Krueger's PCL code. The way I approached it was to create a table for settings with columns for various data types.
