### ISSUE TITLE
Dispatch Messages from asynchronous task

### ISSUE THREAD

**Issue by abrasat** [CodonFramework/Codon#4]
I have have an application which contains an asynchronous task, triggered when data arrives via external network communication. I would like to use the Codon framework Messenger to pass the data from the task to the view-model, is this a valid use-case ? Does the message reception inside the view-model (the ReceiveMessageAsync() method) occur in the context of the UI thread, or is there any context synchronisation needed ? What happens if a burst of a data arrives form the external communication, which generates subsequently a burst of messages over the Messenger ? Will the messages be queued by the Messenger, until the view-model which subscribed for the messages handles them ? Can messages be lost, or the subscriber gets them all, eventually delayed ?

**Comment by DVaughan** [comment]
That is a valid use of the messenger.
By default the message is dispatched on the thread that publishes it. To dispatch on the UI thread, however,   use the requireUIThread parameter of the IMessenger.PublishAsync method. 
The messenger uses async/await for delivering messages. Messages are not queued, they are delivered immediately. The messenger does not currently have the means to dispatch previously published messages to a new subscriber.

**Comment by abrasat** [comment]
In my case there is only one sender and one subscriber for each message type. What happens if "PublishAsync" is called again before the message subscriber did finish the handling of the previous message in the "ReceiveMessageAsync" method, does the second message get lost ?
Is it allowed to publish (another) message from inside the "ReceiveMessageAsync" method ?

**Comment by DVaughan** [comment]
It depends if you're using the same thread to publish. If not then you may need to guard against race conditions in your ReceiveMessageAsync method. But, messages are never lost. If you await the PublishAsync method in ReceiveMessageAsync, then the first call to ReceiveMessageAsync will be the last to complete.

A message is dispatched synchronously to its subscribers. The Messenger does not lock when dispatching messages. It does, however, lock when cleaning up null subscribers. The messenger has a collection of weak references to subscribers for each message type.

**Comment by abrasat** [comment]
Ok, thanks. Does the Messenger support also generic messages (I would like for instance to send different messages having the same base class) ?

**Comment by abrasat** [comment]
I also tried to send a new message from inside ReceiveMessageAsync(), but the subscriber is not triggered. The new message has of course a completely different message type than the message which is handled in ReceiveMessageAsync().

**Comment by DVaughan** [comment]
No, generics aren't supported as you describe.
ReceiveMessageAsync is called on a subscriber if the following evaluates to true:
subscriberType.IsAssignableFrom(typeof(IMessageSubscriber<typeOfMessage>))

You can achieve what you want by wrapping the messages in a class deriving from e.g. MessageBase
and then evaluate if you want to do something with the message in ReceiveMessageAsync.
