### ISSUE TITLE
NavigationService - navigating to different pages with the same ActionCommand ?

### ISSUE THREAD

**Issue by abrasat** [CodonFramework/Codon#5]
Would be possible to navigate to different pages using the same command ?
I have an application containing a list view, and the ItemTemplate is set over a DataTemplateSelector, as the list items have common properties, but also a couple of specific properties.
When selecting an item from a list view, a second detailed page should be displayed for the actually selected item (the OnItemTapped, which generates a ShowDetailInfo command). Could the NavigationService be used to navigate to different types of detail pages, when the command for the tapepd item is generated ? Or is there any other cleaner MVVM solution available to get this kind of functionality ?

**Comment by DVaughan** [comment]
One approach would be to use the INavigationService.NavigationParameter. You could register an action with the routing service. The action would perhaps send a message to one of your components, which would then do the work.

I would, however, probably avoid using the navigation service for this. I would abstract the behavior into an interface and register an object that could be used to control it all. But that's just me.
