### ISSUE TITLE
NavigationService for detail part of MasterDetail page

### ISSUE THREAD

**Issue by abrasat** [CodonFramework/Codon#8]
How must the NavigationService and routes be set to be able to navigate further from the Detail page to another page with additional details ?
I have for instance an application where the Detail page contains an image. When clicking on the image a new "very detailed" page with additional details and a back button should be opened. (something like "/DetailPage/VeryDetailedPage" )

**Comment by DVaughan** [comment]
You could use the NavigationParameter in combination with your routing Action. The routing action could either pass on the request or coordinate displaying of the detail page itself.
